[package]
name = "fso2"
version = "0.1.0"
authors = ["SphericalKat <amolele@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
dotenv = "0.15.0"
log = "0.4"
pretty_env_logger = "0.4.0"

