name: Continuous integration
on: push

jobs:
  # Label of the container job
  tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    # Docker Hub image that `container-job` executes in
    container: rustlang/rust:nightly

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install diesel CLI
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Run diesel migrations
        run: diesel migration run
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/postgres

      - name: Run tests
        run: cargo test
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/postgres